ExampleDataGrid/ExampleDataGrid/Models/ErrorViewModel.cs
using System;

namespace ExampleDataGrid.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExampleDataGrid/ExampleDataGrid/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleDataGrid.Models
{
    public class Person
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public decimal Salary { get; set; }
        public int Age { get; set; }
    }
}

ExampleDataGrid/ExampleDataGrid/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ExampleDataGrid.Models;

namespace ExampleDataGrid.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExampleDataGrid/ExampleDataGrid/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExampleDataGrid.Data;
using ExampleDataGrid.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExampleDataGrid.Controllers
{
    public class PersonsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PersonsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //List<Person> persons = new List<Person>();

            //for (int i = 0; i < 100; i++)
            //{
            //    persons.Add(new Person { Id = Guid.NewGuid(), Name = $"Person {i}", LastName = $"LastName {i}", Age = new Random().Next(18, 80), Salary = new Random().Next(300, 15000) });
            //}

            //_context.Persons.AddRange(persons);
            //_context.SaveChanges();


            return View(_context.Persons.ToList());
        }

        public IActionResult GetData(string name, string lastName, int? age, decimal? salary)
        {

            IQueryable<Person> dataToFilter = null;
            List<Person> result = new List<Person>();


            if (!string.IsNullOrEmpty(name))
            {
                dataToFilter = _context.Persons.Where(x => EF.Functions.Like(x.Name, $"%{name}%"));
            }

            if (!string.IsNullOrEmpty(lastName))
            {
                if (dataToFilter != null)
                {
                    dataToFilter = dataToFilter.Where(x => EF.Functions.Like(x.LastName, $"%{lastName}%"));
                }
                else
                {
                    dataToFilter = _context.Persons.Where(x => EF.Functions.Like(x.LastName, $"%{lastName}%"));
                }
            }

            if (age != null)
            {
                if (dataToFilter != null)
                {
                    dataToFilter = dataToFilter.Where(x => x.Age == age);
                }
                else
                {
                    dataToFilter = _context.Persons.Where(x => x.Age == age);
                }
            }

            if (salary != null)
            {
                if (dataToFilter != null)
                {
                    dataToFilter = dataToFilter.Where(x => x.Salary == salary);
                }
                else
                {
                    dataToFilter = _context.Persons.Where(x => x.Salary == salary);
                }
            }

            if (dataToFilter == null)
            {
                result = _context.Persons.ToList();
            }
            else
            {
                result = dataToFilter.AsNoTracking().ToList();
            }

            return Ok(result);
        }
    }
}

ExampleDataGrid/ExampleDataGrid/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ExampleDataGrid/ExampleDataGrid/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ExampleDataGrid/ExampleDataGrid/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ExampleDataGrid/ExampleDataGrid/Views/Persons/Index.cshtml
@model List<Person>


@{
    ViewData["Title"] = "Index";
}

<style>
    table {
        border-spacing: 0;
        width: 100%;
        border: 1px solid #ddd;
    }

    th {
        cursor: pointer;
    }

    th, td {
        text-align: left;
        padding: 12px;
    }

    tbody tr:nth-child(even) {
        background-color: #f2f2f2
    }

    .input-with-100 {
        width: 100%;
    }

    table.sortable thead tr {
        background-color: #eee;
        color: #666666;
        font-weight: bold;
        cursor: default;
    }
</style>

<h2>Index</h2>


<table border="1">
    <tr>
        <td style="width: 28%"> <input id="inputName" type="text" class="input-with-100" placeholder="Name" onkeydown="doFilter()" /> </td>
        <td style="width: 28%"> <input id="inputLastName" type="text" class="input-with-100" placeholder="LastName" onkeydown="doFilter()" /> </td>
        <td style="width: 15%"> <input id="inputAge" type="text" class="input-with-100" placeholder="Age" onkeydown="doFilter()" /> </td>
        <td style="width: 29%"> <input id="inputSalary" type="text" class="input-with-100" placeholder="Salary" onkeydown="doFilter()" /> </td>
    </tr>
</table>
<table id="tableResult" border="1" class="sortable">
    <thead>
        <tr>
            <th style="width: 28%"><b>Name</b></th>
            <th style="width: 28%"><b>LastName</b></th>
            <th style="width: 15%"><b>Age</b></th>
            <th style="width: 29%"><b>Salary</b></th>
        </tr>
    </thead>
    <tbody id="tbodyTableResult">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.LastName</td>
                <td>@item.Age</td>
                <td>@item.Salary</td>
            </tr>
        }
    </tbody>
</table>

<script src="~/js/sorttable.js"></script>
<script>
    var delayTimer

    function doFilter() {
        clearTimeout(delayTimer)
        delayTimer = setTimeout(function () { filterTable() }, 500)
    }

    function filterTable() {
        var name = document.getElementById('inputName').value
        var lastName = document.getElementById('inputLastName').value
        var age = document.getElementById('inputAge').value
        var salary = document.getElementById('inputSalary').value

        var params = ''

        if (name != '') {
            params += '?name=' + name
        }

        if (lastName != '') {
            if (params.length > 0) {
                params += '&lastName=' + lastName
            } else {
                params += '?lastName=' + lastName
            }
        }

        if (age != '') {
            if (params.length > 0) {
                params += '&age=' + age
            } else {
                params += '?age=' + age
            }
        }

        if (salary != '') {
            if (params.length > 0) {
                params += '&salary=' + salary
            } else {
                params += '?salary=' + salary
            }
        }

        ajaxGet('/Persons/GetData' + params, function (res) {
            insertRows(res)
        })
    }

    function ajaxGet(url, callback) {
        var xmlhttp = new XMLHttpRequest()
        xmlhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                callback(JSON.parse(this.responseText))
            }
        }
        xmlhttp.open("GET", url, true)
        xmlhttp.send()
    }

    function deleteAllRows() {
        document.getElementById('tbodyTableResult').innerHTML = ""
    }

    function insertRows(rows) {
        deleteAllRows()
        var tbody = document.getElementById('tbodyTableResult')
        for (var i = 0; i < rows.length; i++) {
            var row = tbody.insertRow(i)
            row.insertCell(0).innerHTML = rows[i].name
            row.insertCell(1).innerHTML = rows[i].lastName
            row.insertCell(2).innerHTML = rows[i].age
            row.insertCell(3).innerHTML = rows[i].salary
        }
    }


</script>

ExampleDataGrid/ExampleDataGrid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExampleDataGrid</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ExampleDataGrid</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Persons" asp-action="Index">Persons</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ExampleDataGrid</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>